export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="/home/user/.oh-my-zsh"
ZSH_THEME="nodeys"

# Themes that I like: 
# crunch, fox, gnzh
# spaceship(https://github.com/denysdovhan/spaceship-prompt#oh-my-zsh)
# nodeys(https://github.com/tianheg/nodeys-zsh-theme/blob/master/nodeys.zsh-theme)

DISABLE_AUTO_UPDATE="true"
DISABLE_UPDATE_PROMPT="true"

plugins=(
git
zsh-syntax-highlighting 
zsh-autosuggestions     
)

# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#oh-my-zsh
# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md#oh-my-zsh

ZSH_DISABLE_COMPFIX="true"
source $ZSH/oh-my-zsh.sh

# User configuration

alias rezsh="source $HOME/.zshrc"
alias gad="git add --all"
alias gci="git commit -m"
alias gsm="git push origin main"
alias glm="git pull origin main"

# tj/n 的路径
export N_PREFIX="$HOME/.n"
# 当切换 Node.js 版本时保留 npm
export N_PRESERVE_NPM=1
# 将 tj/n 添加到 PATH
export N_PREFIX=$HOME/.n
export PATH=$N_PREFIX/bin:$PATH


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
## __conda_setup="$('/home/gth/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
## if [ $? -eq 0 ]; then
##     eval "$__conda_setup"
## else
##     if [ -f "/home/gth/miniconda3/etc/profile.d/conda.sh" ]; then
##         . "/home/gth/miniconda3/etc/profile.d/conda.sh"
##     else
##         export PATH="/home/gth/miniconda3/bin:$PATH"
##     fi
## fi
## unset __conda_setup
# <<< conda initialize <<<

export PATH=/home/gth/miniconda3/bin:$PATH

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# poetry-python:PYTHON PACKAGING AND DEPENDENCY MANAGEMENT MADE EASY
source $HOME/.poetry/env

# terminal proxy (Ubuntu)
export http_proxy=http://127.0.0.1:1080
export https_proxy=http://127.0.0.1:1080

# vbox
#export http_proxy=http://10.0.2.2:1080
#export https_proxy=http://10.0.2.2:1080

export http_proxy_user=user
export http_proxy_pass=pass

export https_proxy_user=user
export https_proxy_pass=pass
# cancel proxy
## export http_proxy=
## export https_proxy=

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Go Global variables
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# duf
export DUF=/usr/local/duf

# gpg
export GPG_TTY=$(tty)

# for Enable Public Access on your X11 server for Windows.
export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=1

# yarn
export PATH="$PATH:$(yarn global bin)"
